#!/bin/bash
umount -l /usr /var
units="\x2esystem-usr.mount \x2esystem-var.mount \x2esystem-usr-local.mount \x2esystem-var-log.mount"

for unit in $units; do
  echo "Enabling unit file: $unit..."
  systemctl enable $unit
done

systemctl daemon-reload

umount -l /usr /var  # workaround: dpkg still needs to be able to access /usr and /var to complete the transaction
echo "Reboot to complete installation."
true